### ISSUE TITLE
cluster comes up with all pgs stuck inactive/unclean

### ISSUE THREAD

**Issue by ingardm** [komljen/ceph-salt#1]
I've tested both with vagrant and physical machines with more osds/pgs, the result is in both cases the cluster comes up with all pgs stuck unclean/inactive. Output of ceph -s : 

root@node01:/var/log/ceph# ceph -s
    cluster 294bc494-81ba-4c3c-ac5d-af7b3442a2a5
     health HEALTH_WARN 192 pgs stuck inactive; 192 pgs stuck unclean; clock skew detected on mon.node02
     monmap e3: 3 mons at {master=192.168.33.10:6789/0,node01=192.168.33.20:6789/0,node02=192.168.33.30:6789/0}, election epoch 6, quorum 0,1,2 master,node01,node02
     osdmap e7: 4 osds: 4 up, 4 in
      pgmap v16: 192 pgs, 3 pools, 0 bytes data, 0 objects
            130 MB used, 16209 MB / 16339 MB avail
                 192 creating

**Comment by maddy6063** [comment]
Hello,
I am facing this error after I was installing RADOS Gateway on admin node. Befor moving to RADOS Gateway I have checked the status of cluster it was showing CEPH Health OK but now i facing this error. Please share your views to solve the error. 
Thanks n advance!

Error during ceph -s:
cluster a0d2d67e-d551-4c24-833e-993a770fdb2c
     health HEALTH_WARN
            512 pgs degraded
            512 pgs stuck degraded
            512 pgs stuck undersized
            512 pgs undersized
            too many PGs per OSD (632 > max 300)
     monmap e1: 1 mons at {ubadmin=192.168.181.133:6789/0}
            election epoch 1, quorum 0 ubadmin
     osdmap e30: 2 osds: 2 up, 2 in
      pgmap v119: 632 pgs, 9 pools, 1452 bytes data, 47 objects
            13108 MB used, 22465 MB / 37525 MB avail
                 512 active+clean+undersized+degraded
                 120 active+clean
