### ISSUE TITLE
typo in cache config

### ISSUE THREAD

**Issue by EnderMorrison** [komljen/ceph-salt#3]
"flash" should be "flush".

vagrant@master:/srv/pillar$ grep writethrough data/ceph.sls 
    rbd_cache_writethrough_until_flash: "true"

vagrant@master:/srv/pillar$ sudo salt 'node02' cmd.run 'ceph daemon osd.0 config show | grep rbd_cache_write'
node02:
      "rbd_cache_writethrough_until_flush": "false",

**Comment by komljen** [comment]
Thanks for reporting this issue.
Fixed now: https://github.com/komljen/ceph-salt/commit/1326eb87e0d8b5872d7ce68f08a6c63f38a00267
