### ISSUE TITLE
Error connecting to cluster: PermissionError

### ISSUE THREAD

**Issue by LeipeHaribo112** [komljen/ceph-salt#6]
I seem to run into an issue with your scripts. The orchestration finishes, but when I try to 'sudo ceph -s' or 'ceph -s' I get the error in the title. When I 'sudo chown harold:harold ceph.client.admin.keyring' , and then try to 'ceph -s' everything works fine. I suspect there is something wrong with the ownership of the automatically generated keyring? 'chmod 777' does not fix it, it has to be owned by the calling user...

I would like to know if there is a way to fix this in the code?

**Comment by komljen** [comment]
I did some updates, can you try to run everything from scratch now if above issue happened on Vagrant?
